meta_title: "Anthony Amar - Professeur et conférencier en nouvelles technologies."
meta_description: "Anthony Amar est professeur et conférencier spécialisé dans les nouvelles technologies, la programmation et l'entrepreneuriat dans les milieux artistiques."
meta_image: "meta_image.png"
twitter_account: "@studiomatic_"